### ISSUE TITLE
Fix ellipsis insertion

### ISSUE THREAD

**Issue by janhohenheim** [timetabio/code#7]
Post in post view:
![image](https://cloud.githubusercontent.com/assets/9047632/21393901/be22754a-c796-11e6-8be5-c17863c996e8.png)
Post in feed view:
![image](https://cloud.githubusercontent.com/assets/9047632/21393910/c7f4e7b0-c796-11e6-9a60-644797be1f94.png)
Notice the unnecessary ellipsis (...)

**Comment by tautropfli** [comment]
This was fixed a while back but the posts haven't been re-indexed.
I just ran the Task Indexer, so your post should be fixed.

**Comment by janhohenheim** [comment]
:trollface:
